/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "./src/riscv_core.v:9.1-21.10" *)
module riscv_core(clk, rst_n);
  (* src = "./src/riscv_core.v:10.16-10.19" *)
  input clk;
  wire clk;
  (* src = "./src/riscv_core.v:11.16-11.21" *)
  input rst_n;
  wire rst_n;
endmodule
